# Entirety is workflow
name: Hello World

on:
  # workflow dispatch allows you to manually trigger a workflow run and pass inputs to it.
  workflow_dispatch: 
    inputs:
      name:
        description: 'Simple greeting to the world'
        required: true
        default: 'Sharif'

# single job
jobs: 
  say-hello:
    runs-on: ubuntu-latest

    # compute steps to run in the job
    steps:
      - name: Say Hello
        run: echo "Hello ${{ github.event.inputs.name }}!"